# Generated by Django 5.0.3 on 2024-04-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_iot_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
