# Generated by Django 5.0.4 on 2024-04-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_iot_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=225)),
                ('light', models.CharField(max_length=225)),
                ('hum', models.CharField(max_length=225)),
                ('time_created', models.DateTimeField()),
            ],
        ),
    ]
